m4b/faerie

src/elf.rs

These are the names specified in the SysV ELF ABI.

Rename "strtab" and "symtab" to ".strtab" and ".symtab".

---

src/elf.rs

This fixes the bug that the strtab and symtab sections were being marked allocatable.
It also follows up on your comment [here](https://github.com/m4b/faerie/pull/11#discussion_r150076004) and makes the alloc flag default to false :-).

Make sections other than text and data non-alloc.

---

src/artifact.rs
src/bin/main.rs
src/elf.rs
src/mach.rs

This PR is a first cut at addressing https://github.com/m4b/faerie/issues/20 and maybe makes a start toward addressing https://github.com/m4b/faerie/issues/17. Hightlights:
- Adds a new datum to `Data` that determines whether the corresponding ELF section should have the writeable flag set (`writeable`)
- Adds corresponding changes to `Prop`; I think this obeys the warning [here](http://github.com/jfoote/faerie/blob/master/src/artifact.rs#L37) since the change does not reorder the fields
- Assumes `Data` should not be mergeable and `CString` should be mergeable
- Does not address the alignment comment on https://github.com/m4b/faerie/issues/17
- I wasn't quite sure what you had in mind here
- The code does not assert/ensure the defined string is null-terminated
- I didn't add any tests
- …

First cut at specializing data decls/defns

---

src/artifact.rs

I goofed when I designed `RelocOverride` - the addend needs to be signed. (More often than not, it is negative.) Fortunately its a one-character change.

RelocOverride: addend needs to be signed

---

src/artifact.rs
tests/artifact.rs

This removes adding the import to Artifact::imports twice.  It's already handled by declare.
This fixes #26

Make import(...) really just sugar for declare(...)

---

src/artifact.rs
src/elf.rs

The clone derivations are, I think, harmless. They're handy for testing etc.
I hit the `unwrap()` panic in `Elf::link` because I had incorrectly declared a symbol. I wasn't sure if changing the signature to `Result<(), Error>` was appropriate so I just added the reason to `expect`.

Add clone derivations; elaborate linking error

---

src/artifact.rs
tests/artifact.rs
tests/elf.rs

Fixes #30 
Adds a new method `Artifact::undefined_symbols` that gives the set of non-import declarations that have no definitions. Ensures that this is an empty set in the `emit` method.
Additionally, prevents duplicate definitions of symbols.

Ensure all artifact symbols are defined before emitting object

---

src/elf.rs
src/mach.rs

`write` isn't guaranteed to write all of the bytes; it returns a size
saying how many bytes are written, and expects callers to cope with that
number being less than the requested size. Use `write_all` instead,
which either writes the requested size, or returns an error.
See also:
- https://doc.rust-lang.org/std/io/trait.Write.html#tymethod.write
- https://doc.rust-lang.org/std/io/trait.Write.html#method.write_all

Use `write_all` instead of `write`.

---

src/elf.rs

Check that computed sizes for various ELF constructs are the size
they are expected to be with `assert_eq!` rather than logging about
it and proceeding to emit corrupted output. `assert_eq!` is
appropriate here, because if any of these fail, it indicates a bug in
the code here.

Use asserts to check that emitted sizes are as expected.

---

Cargo.toml
src/artifact.rs
src/elf.rs

Previously, a relocation in a data section would use a PC or PLT relative relocation. This meant you couldn't put a function pointer into a data section without using a `RelocOverride`, which we are trying to avoid depending on in `cretonne-faerie`.
This patch lets Elf::link examine the declaration of the `from` field of a relocation, and use a pointer-sized relocation when it is from a data section.
Relocations originating in a FunctionImport, DataImport, or CString will panic. I don't think it makes sense to put in a relocation for any of those types, however, I am open to correction.
Does this break any existing users of the library? I am only aware of my own code (which used a RelocOverride to rectify this problem) and `cretonne-faerie`. Since we are pre 1.0 I think its OK to break …

Change relocations in data sections to be absolute and pointer-sized

---

Cargo.toml
README.md
src/artifact.rs
src/bin/main.rs
src/elf.rs
src/lib.rs
src/mach.rs
src/target.rs
tests/artifact.rs
tests/elf.rs

`targeting` is a new crate that provides a vocabulary for describing targets,
including their architecture and binary file format. The patch here replaces
faerie's `Target` enum and `Object` trait with targeting's `Triple` struct.
This has the following advantages:
- Artifact::emit and Artifact::write no longer have a type parameter, so
users of faeiry don't have to add extra abstraction in order to support
multiple formats dynamically (as Cretonne currently does [here]).
- targeting is rich enough that compilers can use it directly. It supports
the same set of target names that rustc uses. This eliminates the need to
translate between different target enums when using faerie.
[here]: https://github.com/cretonne/cretonne/blob/master/lib/faerie/src/container.rs#L7
One downside is that this …

Port faerie to the targeting crate.

---

Cargo.toml
src/artifact.rs
src/bin/main.rs
src/elf.rs
tests/artifact.rs

"Writable" seems the more common English spelling.
This is mainly because cranelift code currently uses "writable" (without the "e") and faerie uses "writeable" (with the "e"), and I can cope either way, as long as they agree :-).

Rename "writeable" to "writable".

---

src/elf.rs

Without this, the example prints
beef: 0xdeadbef0 - 0xcafebabe
instead of
deadbeef: 0xdeadbef0 - 0xcafebabe

elf: PC32 relocations must use -4 addend, even for CString

---

src/artifact.rs
src/bin/main.rs
src/elf.rs
src/lib.rs
src/mach.rs

Mach support will come in a later PR.
Fixes #49 
While I start working on Mach support, it'd be good if someone could have a quick look at the [last commit](https://github.com/m4b/faerie/commit/31bc62c88b41f40222a17b62dafecea043478f00) to see if this approach looks ok.

Implement DWARF support 

---

reference/Makefile
src/bin/main.rs
src/mach.rs

I don't have an macOS system to test on, so this is barely tested. I've checked that `target/debug/prototype` gives the same output without `--dwarf` (other than for `reloff` values that don't matter), and that llvm-readobj-3.9 shows the sections and relocations with `--dwarf`.

mach: implement debug sections 

---

src/mach.rs

I accidentially used `return` instead of `continue` in #56, so faerie would skip all relocations after the first debug one.

Fix Mach-O debug relocations

---

src/artifact.rs
src/artifact/decl.rs
src/bin/main.rs
src/lib.rs

Presently, `artifact::Decl` is exposed as a public enum. This means that each user of the library needs to know about the internals of `Decl`.
For both #60 and #61, we need to modify or extend the fields inside individual Decl variants. I also would like to add optional alignment information to declarations. To minimize the burden on library users, this PR proposes an alternative interface to constructing Decls that will allow (many kinds of) representation changes without changes to the interface. This PR is not a breaking change, but existing library users should migrate to it. The full Decl enum will remain public, and library users are welcome to continue using it, as long as they don't mind keeping up with changes.
In this PR:
* Move Decl to its own file under artifact, to minimize …

Extensible Decl interface

---

src/artifact.rs
src/artifact/decl.rs
src/bin/main.rs
src/elf.rs
src/lib.rs
src/mach.rs
tests/artifact.rs
tests/elf.rs

The goal of this is to replace `artifact::Prop` with `artifact::ADecl`, where ADecl is a new enum introduced with just the artifact-defined variants of `Decl`.
* Eliminates invariant on structure of `Prop` by keeping two sets and iterating through them with in sequence
* Changes `Decl` to be just two variants: `Import(ImportKind), Artifact(ADecl)`
* delete `artifact::Prop` and just use `ADecl` in its place all the way into the backends.
This enables:
* Some general refactoring, and fixing FIXMEs, in elf.rs.
* We can start putting the additional attributes that backends need into the ADecl fields.
* We can eliminate the special case of CString data by making string contents an attribute of Data
This brought up an important question:
* Do imports belong in Decl at all? Can we expose a …

Carry declarations through

---

Cargo.toml
README.md
src/artifact.rs
src/artifact/decl.rs
src/elf.rs
src/lib.rs
src/mach.rs
tests/elf.rs

Based on #67 
Adds attributes to each declaration that allow the user to control:
* Scope is one of `Scope { Global, Local, Weak }`. Local by default, `is_global()` still gives a bool. Fixes #60 
* Visibility is one of `Visibility { Default, Protected, Hidden }`. Default by default. Fixes #61 
* Optional alignment hint. The alignment hint is used if provided, otherwise the heuristic is used based on whether the section is executable or writable. Fixes #34 
* Data type (strings vs binary data) of Data and DebugSection. Default is binary data.
The data type attribute means:
* CStrings are now just an attribute on Data, rather than a totally separate variant of decl. The builder API stays the same
* Debug sections can be marked as containing strings or not, so we can eventaully remove the …

Expand declaration attributes

---

src/artifact.rs
src/artifact/decl.rs
src/bin/main.rs
src/elf.rs
src/lib.rs
src/mach.rs

See https://github.com/bjorn3/rustc_codegen_cranelift/pull/435#issuecomment-477429904
This hasn't been tested with mach-O yet.

Implement custom sections

---

src/elf.rs
tests/elf.rs

Based off of related #77 
1. using @zhuowei work, add support for sections greater than 65536
2. fix alignment issues in faerie when writing symtab, relocs, and section headers

elf: implements extended section header

---

src/artifact.rs
src/elf.rs
src/mach.rs

cc bjorn3/rustc_codegen_cranelift#435

Implement custom symbols referencing a section for machO

---

.travis.yml
Cargo.toml
examples/prototype.rs

Removes structopt as a dependency of the library.
Addresses https://github.com/m4b/faerie/issues/88

Make `prototype` an example

---

Cargo.toml
src/artifact.rs
src/elf.rs
src/mach.rs

This updates to target-lexicon 0.8.0 and fixes some warnings on recent stable Rust compilers.

Update target lexicon

---

src/artifact.rs
src/artifact/decl.rs
src/elf.rs
src/lib.rs
src/mach.rs
tests/artifact.rs

Allows defining zero-initialized data without allocating memory while writing the object file.
Closes #97.
Ongoing issues:

Add support for .bss sections

---

Cargo.toml
examples/prototype.rs
src/artifact.rs
src/elf.rs
src/lib.rs
src/mach.rs
tests/elf.rs

This commit takes a similar migration path as proposed in
CraneStation/wasmtime#436 and shares much of the same motivation. The
intention here was originally spawned from using `anyhow` everywhere
inside of `wasmtime`!

Migrate from the `Fail` trait to `Error`

---

Cargo.toml
src/artifact.rs
src/elf.rs
src/mach.rs

an ArtifactError can be coerced into a anyhow::Error by consumers of this API, but the inverse is not true. There weren't many places where anyhow::Error was being used, and it was easy to add cases to ArtifactError to cover those cases.
We are trying to convert Lucet to use structured errors everywhere we can, and this helps us get rid of some of the very last we have left. The advantage as a consumer is we can write a thiserror variant like
`FaerieError(#[from] faerie::ArtifactError)` and then we automatically get all our Faerie errors in one variant, versus having to inspect the `anyhow::Error` by eye.

make entire Artifact api return ArtifactError
